export const DEFAULT_SHORT_LEAVE_MINUTES = 120;
export const SHORT_LEAVE_MONTHLY_CAP = 4;
export const AUTO_SHORT_LEAVE_APPLIED_LABEL = 'Automatic short leave.';

export const isAutoGeneratedLeave = (item) => {
  if (!item) return false;
  if (Number(item.auto_generated ?? item.autoGenerated ?? 0) === 1) return true;
  const source = String(item.request_source ?? item.requestSource ?? '');
  return source === 'attendance_late_auto' || source === 'attendance_insufficient_auto';
};

export const leaveRequestStatusLabel = (item) => {
  if (isAutoGeneratedLeave(item)) return 'Automatic';
  return leaveStatusLabel(item?.current_status ?? item?.status);
};

export const humanizeToken = (value) =>
  String(value || '').replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase()).trim();

export const leaveStatusLabel = (status) => {
  const s = String(status || '').toLowerCase();
  if (s === 'approved') return 'Approved';
  if (s === 'pending_l1') return 'Waiting for reporting officer';
  if (s === 'pending_l2') return 'Waiting for HOD';
  if (s === 'rejected') return 'Rejected';
  if (s === 'cancelled' || s === 'canceled') return 'Cancelled';
  return humanizeToken(status) || 'Unknown';
};

export const attendanceStatusLabel = (status) => {
  const s = String(status || '').toLowerCase();
  if (s === 'completed') return 'Finished for the day';
  if (s === 'in_progress') return 'Marked in — not out yet';
  if (s === 'not_marked') return 'No attendance recorded';
  return humanizeToken(status) || '—';
};

export const requestModeLabel = (mode) => {
  const s = String(mode || '').toLowerCase();
  if (s === 'full_day') return 'Full day';
  if (s === 'half_day') return 'Half day';
  if (s === 'short') return 'Short leave';
  return humanizeToken(mode) || '—';
};

export const overlookingStatusLabel = (status) => {
  const s = String(status || '').toLowerCase();
  if (s === 'accepted') return 'Accepted';
  if (s === 'declined') return 'Declined';
  if (s === 'pending') return 'Waiting for response';
  return humanizeToken(status) || '—';
};

export const buildMarkOutWaitHint = (options) => {
  const { earliestMarkOutTime, hasAutoShortLeaveToday = false, hasApprovedLeaveToday = false, approvedLeaveContext = null } = options;
  const base = `Mark-out opens at ${earliestMarkOutTime}.`;
  if (hasApprovedLeaveToday && approvedLeaveContext) {
    const mode = String(approvedLeaveContext.requestMode || '').toLowerCase();
    const session = String(approvedLeaveContext.shortLeaveSession || approvedLeaveContext.halfDaySession || '').toLowerCase();
    if (mode === 'short' && session === 'evening') return `${base} Your approved evening short leave may allow earlier exit.`;
    if (mode === 'half_day' && (session === 'evening' || session === 'afternoon')) return `${base} Your approved half-day may allow earlier exit.`;
  }
  if (hasAutoShortLeaveToday) return `${base} Automatic short leave does not allow earlier exit.`;
  return `${base} Request approved short leave (${DEFAULT_SHORT_LEAVE_MINUTES} min) or half-day in advance for earlier exit.`;
};
