import React, { useMemo } from 'react';
import { isAutoGeneratedLeave } from '../utils/hrStatusLabels';

const DAY_HEADERS = ['S', 'M', 'T', 'W', 'T', 'F', 'S'];

function buildCalendarDays(yearMonth) {
  const [y, m] = String(yearMonth || '').split('-').map(Number);
  if (!y || !m) return [];
  const firstDay = new Date(y, m - 1, 1).getDay();
  const totalDays = new Date(y, m, 0).getDate();
  const cells = [];
  for (let i = 0; i < firstDay; i++) cells.push({ key: `es-${i}`, day: null, dateKey: null });
  for (let d = 1; d <= totalDays; d++) {
    const dk = `${y}-${String(m).padStart(2, '0')}-${String(d).padStart(2, '0')}`;
    cells.push({ key: dk, day: d, dateKey: dk });
  }
  while (cells.length % 7 !== 0) cells.push({ key: `ee-${cells.length}`, day: null, dateKey: null });
  return cells;
}

function analyzeDayMarkers(dateKey, attendanceDateSet, holidayDateSet, bulkDateSet, leaveDetailByDate) {
  if (!dateKey) return { hasAttendance: false, hasHoliday: false, hasBulk: false, hasFullLeave: false, hasApprovedShortLeave: false, hasAutoShortLeave: false, hasPendingShortLeave: false, hasAnyLeave: false, hasAnyDetail: false };
  const leaves = Array.isArray(leaveDetailByDate?.[dateKey]) ? leaveDetailByDate[dateKey] : [];
  let hasFullLeave = false, hasApprovedShortLeave = false, hasAutoShortLeave = false, hasPendingShortLeave = false;
  leaves.forEach((item) => {
    const mode = String(item.requestMode || '').toLowerCase();
    const status = String(item.status || '').toLowerCase();
    if (mode === 'short') {
      if (isAutoGeneratedLeave(item)) hasAutoShortLeave = true;
      else if (status === 'approved') hasApprovedShortLeave = true;
      else if (status.startsWith('pending')) hasPendingShortLeave = true;
      return;
    }
    if (status === 'approved' || status.startsWith('pending')) hasFullLeave = true;
  });
  const hasAttendance = attendanceDateSet.has(dateKey);
  const hasHoliday = holidayDateSet.has(dateKey);
  const hasBulk = bulkDateSet.has(dateKey);
  const hasAnyLeave = leaves.length > 0;
  const hasAnyDetail = hasAttendance || hasAnyLeave || hasHoliday || hasBulk;
  return { hasAttendance, hasHoliday, hasBulk, hasFullLeave, hasApprovedShortLeave, hasAutoShortLeave, hasPendingShortLeave, hasAnyLeave, hasAnyDetail };
}

function getCellClass(markers) {
  if (!markers || !markers.hasAnyDetail) return '';
  if (markers.hasBulk) return 'hrsup-cal-cell--bulk';
  if (markers.hasFullLeave && !markers.hasAttendance) return 'hrsup-cal-cell--leave';
  if (markers.hasAttendance) return 'hrsup-cal-cell--attended';
  if (markers.hasHoliday) return 'hrsup-cal-cell--holiday';
  return '';
}

function getDots(markers) {
  const dots = [];
  if (markers?.hasApprovedShortLeave) dots.push({ color: '#7c3aed', key: 'short' });
  if (markers?.hasAutoShortLeave) dots.push({ color: '#ea580c', key: 'auto' });
  if (markers?.hasPendingShortLeave) dots.push({ color: '#eab308', key: 'pending' });
  if (markers?.hasHoliday) dots.push({ color: '#92400e', key: 'holiday' });
  return dots;
}

export default function CalendarMonthGrid({ yearMonth, calendarData, onDayClick }) {
  const cells = useMemo(() => buildCalendarDays(yearMonth), [yearMonth]);
  const attendanceDateSet = useMemo(() => new Set((calendarData?.attendanceDates || []).map(String)), [calendarData]);
  const holidayDateSet = useMemo(() => new Set((calendarData?.holidayDates || []).map(String)), [calendarData]);
  const bulkDateSet = useMemo(() => new Set((calendarData?.bulkLeaveDates || []).map(String)), [calendarData]);
  const leaveDetailByDate = calendarData?.leaveDetailsByDate || {};

  return (
    <div>
      <div className="hrsup-cal-grid">
        {DAY_HEADERS.map((h, i) => (
          <div key={i} className="hrsup-cal-day-header">{h}</div>
        ))}
        {cells.map((cell) => {
          if (!cell.dateKey) return <div key={cell.key} className="hrsup-cal-cell hrsup-cal-cell--empty" />;
          const markers = analyzeDayMarkers(cell.dateKey, attendanceDateSet, holidayDateSet, bulkDateSet, leaveDetailByDate);
          const dots = getDots(markers);
          const extraClass = getCellClass(markers);
          return (
            <div
              key={cell.key}
              className={`hrsup-cal-cell${extraClass ? ` ${extraClass}` : ''}${markers.hasAnyDetail ? ' hrsup-cal-cell--interactive' : ''}`}
              onClick={() => markers.hasAnyDetail && onDayClick && onDayClick(cell.dateKey, markers)}
              role={markers.hasAnyDetail ? 'button' : undefined}
              tabIndex={markers.hasAnyDetail ? 0 : undefined}
            >
              <span>{cell.day}</span>
              {dots.length > 0 && (
                <div className="hrsup-cal-dots">
                  {dots.map((dot) => (
                    <span key={dot.key} className="hrsup-cal-dot" style={{ backgroundColor: dot.color }} />
                  ))}
                </div>
              )}
            </div>
          );
        })}
      </div>
      <div style={{ display: 'flex', gap: 12, flexWrap: 'wrap', marginTop: 10, fontSize: 11, color: '#64748b' }}>
        <span><span style={{ display: 'inline-block', width: 10, height: 10, borderRadius: 2, background: '#6ee7b7', marginRight: 4, verticalAlign: 'middle' }} />Attended</span>
        <span><span style={{ display: 'inline-block', width: 10, height: 10, borderRadius: 2, background: '#c4b5fd', marginRight: 4, verticalAlign: 'middle' }} />On Leave</span>
        <span><span style={{ display: 'inline-block', width: 10, height: 10, borderRadius: 2, background: '#faf5f0', marginRight: 4, verticalAlign: 'middle' }} />Holiday</span>
        <span><span style={{ display: 'inline-block', width: 10, height: 10, borderRadius: 2, background: '#ffedd5', marginRight: 4, verticalAlign: 'middle' }} />Bulk leave</span>
      </div>
    </div>
  );
}
