import React, { useEffect, useMemo, useState } from 'react';
import { Bars } from 'react-loader-spinner';
import {
  useAcceptHrLieuLeaveMutation,
  useGetHrAttendanceDayViewQuery,
} from '../../../api/services NodeJs/hrLeaveApi';
import { useGetEmpDepartmentsQuery } from '../../../api/services NodeJs/empOrgStructureApi';
import { useGetWorkLocationsQuery } from '../../../api/services NodeJs/jdManagementApi';
import {
  attendanceDayStatusLabel,
  attendanceLocationCaption,
  autoReasonLabel,
  humanizeToken,
  leaveStatusLabel,
  lieuStatusLabel,
  locationValidLabel,
  nopayDayLabel,
  requestModeLabel,
} from '../../../utils/hrStatusLabels';

const toIsoDate = (date = new Date()) => {
  const y = date.getFullYear();
  const m = String(date.getMonth() + 1).padStart(2, '0');
  const d = String(date.getDate()).padStart(2, '0');
  return `${y}-${m}-${d}`;
};

const formatDateHeading = (dateKey) => {
  const parsed = new Date(`${dateKey}T12:00:00`);
  if (Number.isNaN(parsed.getTime())) return dateKey;
  return parsed.toLocaleDateString(undefined, {
    weekday: 'long',
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  });
};

const formatTime = (value) => {
  if (!value) return '';
  const raw = String(value).replace(' ', 'T');
  const parsed = new Date(raw);
  if (Number.isNaN(parsed.getTime())) return String(value).slice(11, 16) || '';
  return parsed.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
};

const formatMinutes = (mins) => {
  const total = Math.max(0, Number(mins) || 0);
  const h = Math.floor(total / 60);
  const m = total % 60;
  return `${h}h ${m}m`;
};

const buildMapUrl = (lat, lng) => {
  if (lat == null || lng == null || lat === '' || lng === '') return '';
  const la = Number(lat);
  const ln = Number(lng);
  if (!Number.isFinite(la) || !Number.isFinite(ln)) return '';
  return `https://www.google.com/maps?q=${la},${ln}`;
};

const leaveTypeLabel = (lr) =>
  lr.leaveTypeName ||
  lr.leave_type_name ||
  humanizeToken(lr.leaveTypeCode || lr.leave_type_code) ||
  'Leave';

const statusTone = (row) => {
  if (row.attendance?.nopay) return 'nopay';
  if (row.pendingLeaves?.length) return 'pending';
  if (row.attendanceStatus === 'completed') return 'completed';
  if (row.attendanceStatus === 'in_progress') return 'in-progress';
  if (row.autoShortLeaves?.length) return 'auto';
  if (row.attendanceStatus === 'not_marked') return 'absent';
  return 'neutral';
};

function DetailRow({ label, value, children, fullWidth = false }) {
  if (value == null && !children) return null;
  return (
    <div className={`att-day-detail-row${fullWidth ? ' att-day-detail-row--full' : ''}`}>
      <span className="att-day-detail-label">{label}</span>
      <span className="att-day-detail-value">{children || value}</span>
    </div>
  );
}

function MarkPointCard({ title, time, locationValid, lat, lng, distanceMeters }) {
  const formatted = formatTime(time);
  const mapUrl = buildMapUrl(lat, lng);
  const locLabel = attendanceLocationCaption({ locationValid, lat, lng, distanceMeters });

  return (
    <div className="att-day-mark-card">
      <div className="att-day-mark-card-title">{title}</div>
      <div className="att-day-mark-card-time">{formatted || '—'}</div>
      {formatted ? (
        <>
          <div className="att-day-mark-card-loc">{locationValidLabel(locationValid)}</div>
          {locLabel !== 'Not checked' ? (
            mapUrl ? (
              <a className="att-day-mark-card-link" href={mapUrl} target="_blank" rel="noreferrer">
                {locLabel}
              </a>
            ) : (
              <div className="att-day-mark-card-meta">{locLabel}</div>
            )
          ) : null}
        </>
      ) : (
        <div className="att-day-mark-card-meta att-day-muted">Not recorded</div>
      )}
    </div>
  );
}

function LeaveRequestCard({ leave }) {
  const auto = Number(leave.autoGenerated || leave.auto_generated) === 1;
  const mode = leave.requestMode || leave.request_mode;
  const session = leave.halfDaySession || leave.half_day_session;
  const minutes = leave.shortLeaveMinutes ?? leave.short_leave_minutes;
  const status = leave.currentStatus || leave.current_status;

  return (
    <article className={`att-day-leave-card${auto ? ' att-day-leave-card--auto' : ''}`}>
      <div className="att-day-leave-card-head">
        <strong>{leaveTypeLabel(leave)}</strong>
        <span className={`att-day-status-pill att-day-status-pill--${String(status || '').toLowerCase()}`}>
          {auto ? 'Automatic' : leaveStatusLabel(status)}
        </span>
      </div>
      <div className="att-day-leave-card-grid">
        {mode ? <DetailRow label="Mode" value={requestModeLabel(mode)} /> : null}
        {session ? <DetailRow label="Session" value={humanizeToken(session)} /> : null}
        {minutes ? <DetailRow label="Duration" value={`${minutes} minutes`} /> : null}
        {auto && (leave.autoReason || leave.auto_reason) ? (
          <DetailRow label="Reason" value={autoReasonLabel(leave.autoReason || leave.auto_reason)} />
        ) : null}
        {leave.level1ApproverName || leave.level1_approver_name ? (
          <DetailRow label="Reporting officer" value={leave.level1ApproverName || leave.level1_approver_name} />
        ) : null}
        {leave.level2ApproverName || leave.level2_approver_name ? (
          <DetailRow label="HOD" value={leave.level2ApproverName || leave.level2_approver_name} />
        ) : null}
        {(leave.reason || leave.reason_text) ? (
          <DetailRow label="Note" value={leave.reason || leave.reason_text} fullWidth />
        ) : null}
      </div>
    </article>
  );
}

function EmployeeDetailPanel({
  row,
  selectedDate,
  isNonWorkingDay,
  policy,
  acceptingKey,
  onAcceptLieu,
}) {
  if (!row) {
    return (
      <div className="att-day-detail-empty">
        <h3>Select an employee</h3>
        <p>Choose someone from the list to view attendance and leave details for the selected date.</p>
      </div>
    );
  }

  const att = row.attendance;
  const ctx = row.leaveContext;
  const leaveRequests = row.leaveRequests || [];
  const lateDeparture = row.lateDeparture;
  const requiredMinutes = Number(ctx?.requiredDailyMinutes ?? policy?.requiredDailyMinutes ?? 570);

  return (
    <div className="att-day-detail-panel">
      <header className="att-day-detail-header">
        <div>
          <h3 className="att-day-detail-name">{row.employeeName}</h3>
          <p className="att-day-detail-meta">
            {row.empNo || '—'} · {row.department || '—'}
            {row.designation ? ` · ${row.designation}` : ''}
          </p>
          {row.workLocation ? (
            <p className="att-day-detail-submeta">Work location: {row.workLocation}</p>
          ) : null}
        </div>
        <span className={`att-day-status-pill att-day-status-pill--${row.attendanceStatus}`}>
          {attendanceDayStatusLabel(row.attendanceStatus)}
        </span>
      </header>

      <section className="att-day-detail-section">
        <h4>Attendance</h4>
        <div className="att-day-mark-grid">
          <MarkPointCard
            title="Mark in"
            time={att?.markIn}
            locationValid={att?.markInLocationValid}
            lat={att?.markInLatitude}
            lng={att?.markInLongitude}
            distanceMeters={att?.markInDistanceMeters}
          />
          <MarkPointCard
            title="Mark out"
            time={att?.markOut}
            locationValid={att?.markOutLocationValid}
            lat={att?.markOutLatitude}
            lng={att?.markOutLongitude}
            distanceMeters={att?.markOutDistanceMeters}
          />
        </div>
        <div className="att-day-detail-stats">
          <div className="att-day-stat-chip">
            <span>Worked</span>
            <strong>{att ? formatMinutes(att.workingMinutes) : '—'}</strong>
          </div>
          <div className="att-day-stat-chip">
            <span>Required</span>
            <strong>{formatMinutes(requiredMinutes)}</strong>
          </div>
          {att?.lateMinutes != null ? (
            <div className="att-day-stat-chip att-day-stat-chip--warn">
              <span>Late</span>
              <strong>{formatMinutes(att.lateMinutes)}</strong>
            </div>
          ) : null}
          {att?.shortfallMinutes != null ? (
            <div className="att-day-stat-chip att-day-stat-chip--warn">
              <span>Shortfall</span>
              <strong>{formatMinutes(att.shortfallMinutes)}</strong>
            </div>
          ) : null}
          {att?.weeklyGraceUsed ? (
            <div className="att-day-stat-chip att-day-stat-chip--info">
              <span>Weekly grace</span>
              <strong>Used</strong>
            </div>
          ) : null}
          {att?.payStatus && att.payStatus !== 'paid' ? (
            <div className="att-day-stat-chip att-day-stat-chip--danger">
              <span>Pay</span>
              <strong>{humanizeToken(att.payStatus)}</strong>
            </div>
          ) : null}
        </div>
        {att?.nopay ? (
          <div className="att-day-alert att-day-alert--danger">
            <strong>{nopayDayLabel(att.nopayReason)}</strong>
          </div>
        ) : null}
        {att?.autoShortLeave ? (
          <div className="att-day-alert att-day-alert--info">
            <strong>Automatic short leave applied</strong>
            <p>
              {typeof att.autoShortLeave === 'string'
                ? autoReasonLabel(att.autoShortLeave)
                : autoReasonLabel(att.autoShortLeave.autoReason || att.autoShortLeave.auto_reason) ||
                  'Recorded from attendance policy.'}
            </p>
          </div>
        ) : null}
      </section>

      {ctx?.hasApprovedLeave ? (
        <section className="att-day-detail-section">
          <h4>Approved leave context</h4>
          <div className="att-day-context-card">
            <p>{ctx.warningMessage || 'Approved leave affects attendance requirements for this day.'}</p>
            <div className="att-day-detail-grid">
              {ctx.requestMode ? <DetailRow label="Mode" value={requestModeLabel(ctx.requestMode)} /> : null}
              {ctx.halfDaySession ? <DetailRow label="Session" value={humanizeToken(ctx.halfDaySession)} /> : null}
              {ctx.shortLeaveMinutes ? <DetailRow label="Short leave" value={`${ctx.shortLeaveMinutes} min`} /> : null}
              {ctx.expectedMarkInTime ? <DetailRow label="May arrive by" value={ctx.expectedMarkInTime} /> : null}
              {ctx.expectedMarkOutTime ? <DetailRow label="May leave by" value={ctx.expectedMarkOutTime} /> : null}
              {ctx.lateAllowanceMinutes ? (
                <DetailRow label="Late allowance" value={`${ctx.lateAllowanceMinutes} min`} />
              ) : null}
            </div>
          </div>
        </section>
      ) : null}

      <section className="att-day-detail-section">
        <h4>Leave records ({leaveRequests.length})</h4>
        {leaveRequests.length === 0 ? (
          <p className="att-day-muted">No leave requests linked to this date.</p>
        ) : (
          <div className="att-day-leave-list">
            {leaveRequests.map((leave) => (
              <LeaveRequestCard key={leave.id || `${leave.leaveTypeCode}-${leave.currentStatus}`} leave={leave} />
            ))}
          </div>
        )}
      </section>

      {lateDeparture ? (
        <section className="att-day-detail-section">
          <h4>Late stay request</h4>
          <div className="att-day-context-card">
            <div className="att-day-detail-grid">
              <DetailRow
                label="Status"
                value={humanizeToken(lateDeparture.current_status || lateDeparture.status)}
              />
              {lateDeparture.requested_departure_time || lateDeparture.requestedDepartureTime ? (
                <DetailRow
                  label="Requested until"
                  value={formatTime(lateDeparture.requested_departure_time || lateDeparture.requestedDepartureTime)}
                />
              ) : null}
              {lateDeparture.reason ? <DetailRow label="Reason" value={lateDeparture.reason} /> : null}
            </div>
          </div>
        </section>
      ) : null}

      {isNonWorkingDay ? (
        <section className="att-day-detail-section">
          <h4>Lieu leave</h4>
          {row.lieuLeaveAvailable ? (
            <div className="att-day-context-card">
              <DetailRow label="Available balance" value={`${Number(row.lieuBalance || 0)} day(s)`} />
              {row.lieuAccrual ? (
                <>
                  <DetailRow label="Accrued this day" value={`+${row.lieuAccrual.dayUnit} day`} />
                  <DetailRow label="Status" value={lieuStatusLabel(row.lieuAccrual.status)} />
                  {row.lieuAccrual.expiresAt ? (
                    <DetailRow label="Expires" value={row.lieuAccrual.expiresAt} />
                  ) : null}
                </>
              ) : row.canAcceptLieu ? (
                <div className="att-day-lieu-actions">
                  <button
                    type="button"
                    className="att-day-btn att-day-btn-primary"
                    disabled={acceptingKey === `${row.employeeId}-0.5`}
                    onClick={() => onAcceptLieu(row.employeeId, 0.5)}
                  >
                    Accept 0.5 day
                  </button>
                  <button
                    type="button"
                    className="att-day-btn att-day-btn-primary"
                    disabled={acceptingKey === `${row.employeeId}-1`}
                    onClick={() => onAcceptLieu(row.employeeId, 1)}
                  >
                    Accept 1 day
                  </button>
                </div>
              ) : (
                <p className="att-day-muted">No lieu accrual for this date yet.</p>
              )}
            </div>
          ) : (
            <p className="att-day-muted">Lieu leave is not enabled for this employee.</p>
          )}
        </section>
      ) : null}
    </div>
  );
}

export default function AttendanceDayView() {
  const [selectedDate, setSelectedDate] = useState(toIsoDate());
  const [search, setSearch] = useState('');
  const [departmentCode, setDepartmentCode] = useState('');
  const [workLocationCode, setWorkLocationCode] = useState('');
  const [acceptingKey, setAcceptingKey] = useState('');
  const [selectedEmployeeId, setSelectedEmployeeId] = useState(null);

  const { data: departmentsData } = useGetEmpDepartmentsQuery();
  const { data: workLocationsData } = useGetWorkLocationsQuery();

  const departments = useMemo(() => {
    const list = Array.isArray(departmentsData)
      ? departmentsData
      : Array.isArray(departmentsData?.data)
        ? departmentsData.data
        : [];
    return [...list].sort((a, b) =>
      String(a.department_name || a.dept_code || '').localeCompare(
        String(b.department_name || b.dept_code || ''),
      ),
    );
  }, [departmentsData]);

  const workLocations = useMemo(() => {
    const list = Array.isArray(workLocationsData)
      ? workLocationsData
      : Array.isArray(workLocationsData?.data)
        ? workLocationsData.data
        : [];
    return [...list].sort((a, b) =>
      String(a.locationName || a.locationCode || '').localeCompare(
        String(b.locationName || b.locationCode || ''),
      ),
    );
  }, [workLocationsData]);

  const { data: response, isFetching, refetch } = useGetHrAttendanceDayViewQuery({
    date: selectedDate,
    search: search.trim() || undefined,
    departmentCode: departmentCode || undefined,
    workLocation: workLocationCode || undefined,
  });
  const [acceptLieuLeave] = useAcceptHrLieuLeaveMutation();

  const payload = response?.data?.data || response?.data || response || null;
  const employees = payload?.employees || [];
  const summary = payload?.summary || {};
  const policy = payload?.policy || {};
  const holiday = payload?.holiday;
  const isNonWorkingDay = Boolean(payload?.isNonWorkingDay);

  const dayBanner = useMemo(() => {
    if (payload?.isHoliday && holiday?.name) return `Holiday — ${holiday.name}`;
    if (payload?.isWeekend) return 'Weekend';
    return 'Regular working day';
  }, [payload, holiday]);

  const selectedRow = useMemo(
    () => employees.find((row) => Number(row.employeeId) === Number(selectedEmployeeId)) || null,
    [employees, selectedEmployeeId],
  );

  useEffect(() => {
    if (!employees.length) {
      setSelectedEmployeeId(null);
      return;
    }
    const stillVisible = employees.some((row) => Number(row.employeeId) === Number(selectedEmployeeId));
    if (!stillVisible) {
      setSelectedEmployeeId(employees[0].employeeId);
    }
  }, [employees, selectedEmployeeId]);

  const shiftDate = (deltaDays) => {
    const parsed = new Date(`${selectedDate}T12:00:00`);
    if (Number.isNaN(parsed.getTime())) return;
    parsed.setDate(parsed.getDate() + deltaDays);
    setSelectedDate(toIsoDate(parsed));
  };

  const handleAcceptLieu = async (employeeId, dayUnit) => {
    const key = `${employeeId}-${dayUnit}`;
    setAcceptingKey(key);
    try {
      await acceptLieuLeave({
        employeeId,
        workDate: selectedDate,
        dayUnit,
      }).unwrap();
      await refetch();
    } catch (error) {
      window.alert(error?.data?.message || error?.message || 'Could not accept lieu leave');
    } finally {
      setAcceptingKey('');
    }
  };

  return (
    <div className="att-day-view">
      <div className="att-day-hero">
        <div className="att-day-hero-top">
          <div className="att-day-date-nav">
            <button type="button" className="att-day-nav-btn" onClick={() => shiftDate(-1)} aria-label="Previous day">
              ‹
            </button>
            <div className="att-day-date-block">
              <span className="att-day-date-trigger">{formatDateHeading(selectedDate)}</span>
              <input
                type="date"
                className="att-day-date-input-hidden"
                value={selectedDate}
                onChange={(e) => setSelectedDate(e.target.value || toIsoDate())}
                aria-label="Choose attendance date"
              />
            </div>
            <button type="button" className="att-day-nav-btn" onClick={() => shiftDate(1)} aria-label="Next day">
              ›
            </button>
          </div>
          <span className="att-day-daytype">{dayBanner}</span>
        </div>

        <div className="att-day-toolbar">
          <label className="att-day-filter-field">
            <span>Department</span>
            <select
              value={departmentCode}
              onChange={(e) => setDepartmentCode(e.target.value)}
              aria-label="Filter by department"
            >
              <option value="">All departments</option>
              {departments.map((dept) => {
                const value = String(dept.dept_code || dept.id || '').trim();
                if (!value) return null;
                return (
                  <option key={dept.id || value} value={value}>
                    {dept.department_name || dept.dept_code || `Department ${dept.id}`}
                  </option>
                );
              })}
            </select>
          </label>
          <label className="att-day-filter-field">
            <span>Work location</span>
            <select
              value={workLocationCode}
              onChange={(e) => setWorkLocationCode(e.target.value)}
              aria-label="Filter by work location"
            >
              <option value="">All locations</option>
              {workLocations.map((loc) => {
                const value = String(loc.locationCode || '').trim();
                if (!value) return null;
                return (
                  <option key={loc.id || value} value={value}>
                    {loc.locationName || loc.locationCode}
                  </option>
                );
              })}
            </select>
          </label>
          <label className="att-day-search-field att-day-search-field--toolbar">
            <span>Search employee</span>
            <input
              type="text"
              placeholder="Name, EMP no, designation..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
            />
          </label>
        </div>

        <div className="att-day-kpi-grid">
          <div className="att-day-kpi">
            <span>Total</span>
            <strong>{summary.totalEmployees ?? employees.length}</strong>
          </div>
          <div className="att-day-kpi att-day-kpi--ok">
            <span>Attended</span>
            <strong>{summary.attendedCount ?? 0}</strong>
          </div>
          <div className="att-day-kpi att-day-kpi--ok">
            <span>Completed</span>
            <strong>{summary.completedCount ?? 0}</strong>
          </div>
          <div className="att-day-kpi att-day-kpi--warn">
            <span>Not marked</span>
            <strong>{summary.notMarkedCount ?? 0}</strong>
          </div>
          <div className="att-day-kpi">
            <span>Pending leave</span>
            <strong>{summary.pendingLeaveCount ?? 0}</strong>
          </div>
          <div className="att-day-kpi att-day-kpi--info">
            <span>Auto short leave</span>
            <strong>{summary.autoShortLeaveCount ?? 0}</strong>
          </div>
          <div className="att-day-kpi att-day-kpi--danger">
            <span>No pay</span>
            <strong>{summary.nopayCount ?? 0}</strong>
          </div>
        </div>

        <p className="att-day-policy-note">
          Mark-in {policy.markInWindow?.start || '08:00'}–{policy.markInWindow?.end || '08:15'} · Mark-out from{' '}
          {policy.markOutFrom || '17:30'} · Required {policy.requiredDailyMinutes || 570} min · Weekly grace{' '}
          {policy.weeklyGraceAllowance || 2}/week · Short leave {policy.shortLeaveMonthlyCap || 4}/month
          {isNonWorkingDay
            ? ` · Lieu leave max ${policy.lieuLeaveMonthlyCap || 2}/month, valid ${policy.lieuLeaveValidityDays || 30} days`
            : ''}
        </p>
      </div>

      {isFetching ? (
        <div className="att-day-loading">
          <Bars height="48" width="48" color="#004b71" visible />
        </div>
      ) : (
        <div className="att-day-split">
          <aside className="att-day-employee-list" aria-label="Employees for selected date">
            {employees.length === 0 ? (
              <div className="att-day-empty">No employees found for this date.</div>
            ) : (
              employees.map((row) => {
                const tone = statusTone(row);
                const leaveCount = (row.leaveRequests || []).length;
                const isSelected = Number(row.employeeId) === Number(selectedEmployeeId);

                return (
                  <button
                    key={row.employeeId}
                    type="button"
                    className={`att-day-employee-item${isSelected ? ' att-day-employee-item--active' : ''}`}
                    onClick={() => setSelectedEmployeeId(row.employeeId)}
                  >
                    <span className={`att-day-employee-dot att-day-employee-dot--${tone}`} aria-hidden />
                    <span className="att-day-employee-item-body">
                      <span className="att-day-employee-item-name">{row.employeeName}</span>
                      <span className="att-day-employee-item-meta">
                        {row.empNo || '—'} · {attendanceDayStatusLabel(row.attendanceStatus)}
                        {leaveCount ? ` · ${leaveCount} leave` : ''}
                      </span>
                    </span>
                  </button>
                );
              })
            )}
          </aside>

          <EmployeeDetailPanel
            row={selectedRow}
            selectedDate={selectedDate}
            isNonWorkingDay={isNonWorkingDay}
            policy={policy}
            acceptingKey={acceptingKey}
            onAcceptLieu={handleAcceptLieu}
          />
        </div>
      )}
    </div>
  );
}
