import React, { useMemo, useState } from 'react';
import { Bars } from 'react-loader-spinner';
import {
  useAcceptHrLieuLeaveMutation,
  useGetHrAttendanceDayViewQuery,
} from '../../../api/services NodeJs/hrLeaveApi';
import {
  attendanceLocationCaption,
  autoReasonLabel,
  humanizeToken,
  leaveStatusLabel,
  lieuStatusLabel,
  nopayDayLabel,
  requestModeLabel,
} from '../../../utils/hrStatusLabels';

const toIsoDate = (date = new Date()) => {
  const y = date.getFullYear();
  const m = String(date.getMonth() + 1).padStart(2, '0');
  const d = String(date.getDate()).padStart(2, '0');
  return `${y}-${m}-${d}`;
};

const formatTime = (value) => {
  if (!value) return '';
  const raw = String(value).replace(' ', 'T');
  const parsed = new Date(raw);
  if (Number.isNaN(parsed.getTime())) return String(value).slice(11, 16) || '';
  return parsed.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
};

const formatMinutes = (mins) => {
  const total = Math.max(0, Number(mins) || 0);
  const h = Math.floor(total / 60);
  const m = total % 60;
  return `${h}h ${m}m`;
};

const buildMapUrl = (lat, lng) => {
  if (lat == null || lng == null || lat === '' || lng === '') return '';
  const la = Number(lat);
  const ln = Number(lng);
  if (!Number.isFinite(la) || !Number.isFinite(ln)) return '';
  return `https://www.google.com/maps?q=${la},${ln}`;
};

const leaveTypeLabel = (lr) =>
  lr.leaveTypeName ||
  lr.leave_type_name ||
  humanizeToken(lr.leaveTypeCode || lr.leave_type_code) ||
  'Leave';

const formatLeaveLine = (lr) => {
  const typeName = leaveTypeLabel(lr);
  const status = leaveStatusLabel(lr.current_status || lr.currentStatus);
  const mode = lr.request_mode || lr.requestMode;
  const modeText = mode ? requestModeLabel(mode) : '';
  const auto = Number(lr.auto_generated || lr.autoGenerated) === 1;
  const autoReason = auto ? autoReasonLabel(lr.auto_reason || lr.autoReason) : '';
  const minutes = lr.short_leave_minutes || lr.shortLeaveMinutes;

  if (auto && autoReason) return `${autoReason} — ${status}`;
  if (minutes) return `${typeName} (${minutes} min) — ${status}`;
  return `${typeName}${modeText ? ` (${modeText})` : ''} — ${status}`;
};

const buildLeaveContextItem = (ctx) => {
  if (!ctx?.hasApprovedLeave) return null;

  const mode = String(ctx.requestMode || '').toLowerCase();
  if (mode === 'full_day') {
    return {
      key: 'leave-context-full',
      label: 'Full-day leave — Approved',
      detail: ctx.warningMessage || null,
      variant: 'approved',
    };
  }

  if (mode === 'half_day') {
    const session = ctx.halfDaySession === 'evening' ? 'Evening' : 'Morning';
    return {
      key: 'leave-context-half',
      label: `${session} half-day — Approved`,
      detail: ctx.warningMessage || null,
      variant: 'approved',
    };
  }

  if (mode === 'short') {
    const mins = Math.max(0, Number(ctx.shortLeaveMinutes || 0)) || 120;
    const session = String(ctx.shortLeaveSession || ctx.halfDaySession || 'morning');
    const sessionLabel = session === 'evening' ? 'Evening' : 'Morning';
    let detail = null;
    if (session === 'evening' && ctx.expectedMarkOutTime) {
      detail = `May leave by ${ctx.expectedMarkOutTime}`;
    } else if (ctx.expectedMarkInTime) {
      detail = `May arrive by ${ctx.expectedMarkInTime}`;
    } else if (ctx.warningMessage) {
      detail = ctx.warningMessage;
    }
    return {
      key: 'leave-context-short',
      label: `${sessionLabel} short leave (${mins} min) — Approved`,
      detail,
      variant: 'approved',
    };
  }

  return {
    key: 'leave-context-other',
    label: 'Approved leave',
    detail: ctx.warningMessage || null,
    variant: 'approved',
  };
};

const collectLeaveItems = (row) => {
  const items = [];
  const seen = new Set();

  const addItem = (item) => {
    if (!item?.label) return;
    const dedupeKey = item.key || item.label;
    if (seen.has(dedupeKey)) return;
    seen.add(dedupeKey);
    items.push(item);
  };

  const contextItem = buildLeaveContextItem(row.leaveContext);
  if (contextItem) addItem(contextItem);

  const contextCoversAutoShort = Boolean(
    row.leaveContext?.hasApprovedLeave
    && String(row.leaveContext?.requestMode || '').toLowerCase() === 'short',
  );

  row.autoShortLeaves?.forEach((lr) => {
    if (contextCoversAutoShort) return;
    addItem({
      key: `auto-${lr.id || lr.leave_request_id || formatLeaveLine(lr)}`,
      label: formatLeaveLine(lr),
      detail: lr.reason || lr.reason_text || null,
      variant: 'auto',
    });
  });

  row.pendingLeaves?.forEach((lr) => {
    addItem({
      key: `pending-${lr.id || lr.leave_request_id || formatLeaveLine(lr)}`,
      label: formatLeaveLine(lr),
      detail: lr.reason || null,
      variant: 'pending',
    });
  });

  row.approvedLeaves?.forEach((lr) => {
    if (Number(lr.auto_generated || lr.autoGenerated)) return;
    if (contextItem && String(lr.request_mode || lr.requestMode || '').toLowerCase() === 'short') return;
    addItem({
      key: `approved-${lr.id || lr.leave_request_id || formatLeaveLine(lr)}`,
      label: formatLeaveLine(lr),
      detail: lr.reason || null,
      variant: 'approved',
    });
  });

  if (row.attendance?.weeklyGraceUsed) {
    addItem({
      key: 'weekly-grace',
      label: 'Used weekly grace exit',
      detail: null,
      variant: 'info',
    });
  }

  if (row.attendance?.nopay) {
    addItem({
      key: 'nopay',
      label: nopayDayLabel(row.attendance.nopayReason),
      detail: row.attendance.nopayReason || null,
      variant: 'nopay',
    });
  }

  return items;
};

function TimeLocationCell({ time, locationValid, lat, lng, distanceMeters }) {
  const formatted = formatTime(time);
  if (!formatted) return <span className="att-day-muted">—</span>;

  const mapUrl = buildMapUrl(lat, lng);
  const locLabel = attendanceLocationCaption({ locationValid, lat, lng, distanceMeters });
  const showLocationLine = locLabel !== 'Not checked';

  return (
    <div className="att-day-time-stack">
      <div className="att-day-time-main">{formatted}</div>
      {showLocationLine ? (
        mapUrl ? (
          <a className="att-day-time-loc" href={mapUrl} target="_blank" rel="noreferrer">
            {locLabel}
          </a>
        ) : (
          <div className="att-day-time-loc">{locLabel}</div>
        )
      ) : null}
    </div>
  );
}

export default function AttendanceDayView() {
  const [selectedDate, setSelectedDate] = useState(toIsoDate());
  const [search, setSearch] = useState('');
  const [acceptingKey, setAcceptingKey] = useState('');

  const { data: response, isFetching, refetch } = useGetHrAttendanceDayViewQuery({
    date: selectedDate,
    search: search.trim() || undefined,
  });
  const [acceptLieuLeave] = useAcceptHrLieuLeaveMutation();

  const payload = response?.data?.data || response?.data || response || null;
  const employees = payload?.employees || [];
  const summary = payload?.summary || {};
  const policy = payload?.policy || {};
  const holiday = payload?.holiday;
  const isNonWorkingDay = Boolean(payload?.isNonWorkingDay);

  const dayBanner = useMemo(() => {
    if (payload?.isHoliday && holiday?.name) {
      return `Holiday — ${holiday.name}`;
    }
    if (payload?.isWeekend) return 'Weekend';
    return 'Regular working day';
  }, [payload, holiday]);

  const columnCount = isNonWorkingDay ? 6 : 5;

  const handleAcceptLieu = async (employeeId, dayUnit) => {
    const key = `${employeeId}-${dayUnit}`;
    setAcceptingKey(key);
    try {
      await acceptLieuLeave({
        employeeId,
        workDate: selectedDate,
        dayUnit,
      }).unwrap();
      await refetch();
    } catch (error) {
      window.alert(error?.data?.message || error?.message || 'Could not accept lieu leave');
    } finally {
      setAcceptingKey('');
    }
  };

  return (
    <div className="att-day-view">
      <div className="att-day-toolbar">
        <div className="att-day-toolbar-row">
          <label className="att-day-field">
            <span>Date</span>
            <input
              type="date"
              value={selectedDate}
              onChange={(e) => setSelectedDate(e.target.value || toIsoDate())}
            />
          </label>
          <label className="att-day-field att-day-field-grow">
            <span>Search employee</span>
            <input
              type="text"
              placeholder="Name, EMP no, department..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
            />
          </label>
          <div className="att-day-daytype">{dayBanner}</div>
        </div>

        <div className="att-day-summary-row">
          <div className="att-day-summary-chip">Total: {summary.totalEmployees ?? employees.length}</div>
          <div className="att-day-summary-chip att-day-summary-ok">Attended: {summary.attendedCount ?? 0}</div>
          <div className="att-day-summary-chip att-day-summary-ok">Completed: {summary.completedCount ?? 0}</div>
          <div className="att-day-summary-chip att-day-summary-warn">Not marked: {summary.notMarkedCount ?? 0}</div>
          <div className="att-day-summary-chip">Pending leave: {summary.pendingLeaveCount ?? 0}</div>
          <div className="att-day-summary-chip">Auto short leave: {summary.autoShortLeaveCount ?? 0}</div>
          <div className="att-day-summary-chip att-day-summary-warn">No pay: {summary.nopayCount ?? 0}</div>
        </div>

        <div className="att-day-policy-note">
          Mark-in {policy.markInWindow?.start || '08:00'}–{policy.markInWindow?.end || '08:15'} · Mark-out from{' '}
          {policy.markOutFrom || '17:30'} · Required           {policy.requiredDailyMinutes || 570} min · Weekly grace{' '}
          {policy.weeklyGraceAllowance || 2}/week · Short leave {policy.shortLeaveMonthlyCap || 4}/month
          {isNonWorkingDay
            ? ` · Lieu leave max ${policy.lieuLeaveMonthlyCap || 2}/month, valid ${policy.lieuLeaveValidityDays || 30} days`
            : ''}
        </div>
      </div>

      {isFetching ? (
        <div className="att-day-loading">
          <Bars height="48" width="48" color="#004b71" visible />
        </div>
      ) : (
        <div className="att-day-table-wrap">
          <table className="att-day-table">
            <thead>
              <tr>
                <th>Employee</th>
                <th>Mark in</th>
                <th>Mark out</th>
                <th>Worked</th>
                <th>Leave</th>
                {isNonWorkingDay ? <th>Lieu</th> : null}
              </tr>
            </thead>
            <tbody>
              {employees.length === 0 ? (
                <tr>
                  <td colSpan={columnCount} className="att-day-empty">
                    No employees found for this date.
                  </td>
                </tr>
              ) : (
                employees.map((row) => {
                  const att = row.attendance;
                  const attended = row.attendanceStatus !== 'not_marked';
                  const leaveItems = collectLeaveItems(row);

                  return (
                    <tr key={row.employeeId}>
                      <td>
                        <div className="att-day-emp-name">{row.employeeName}</div>
                        <div className="att-day-emp-meta">
                          {row.empNo || '—'} · {row.department || '—'}
                        </div>
                      </td>
                      <td>
                        {attended ? (
                          <TimeLocationCell
                            time={att?.markIn}
                            locationValid={att?.markInLocationValid}
                            lat={att?.markInLatitude}
                            lng={att?.markInLongitude}
                            distanceMeters={att?.markInDistanceMeters}
                          />
                        ) : (
                          <span className="att-day-muted">—</span>
                        )}
                      </td>
                      <td>
                        {attended ? (
                          <TimeLocationCell
                            time={att?.markOut}
                            locationValid={att?.markOutLocationValid}
                            lat={att?.markOutLatitude}
                            lng={att?.markOutLongitude}
                            distanceMeters={att?.markOutDistanceMeters}
                          />
                        ) : (
                          <span className="att-day-muted">—</span>
                        )}
                      </td>
                      <td className="att-day-time-cell">{att ? formatMinutes(att.workingMinutes) : '—'}</td>
                      <td>
                        <div className="att-day-tags">
                          {leaveItems.length === 0 ? (
                            <span className="att-day-muted">
                              {!attended ? 'No leave recorded' : '—'}
                            </span>
                          ) : (
                            leaveItems.map((item) => (
                              <div
                                key={item.key}
                                className={`att-day-leave-item att-day-leave-item--${item.variant}`}
                              >
                                <span
                                  className={`att-day-tag${item.variant === 'nopay' ? ' att-day-tag-nopay' : ''}`}
                                >
                                  {item.label}
                                </span>
                                {item.detail && item.detail !== item.label ? (
                                  <div className="att-day-leave-detail">{item.detail}</div>
                                ) : null}
                              </div>
                            ))
                          )}
                        </div>
                      </td>
                      {isNonWorkingDay ? (
                        <td>
                          {row.lieuLeaveAvailable ? (
                            <>
                              <span className="att-day-lieu-balance">{Number(row.lieuBalance || 0)} day</span>
                              {row.lieuAccrual ? (
                                <div className="att-day-lieu-acc">
                                  +{row.lieuAccrual.dayUnit} day · {lieuStatusLabel(row.lieuAccrual.status)}
                                </div>
                              ) : row.canAcceptLieu ? (
                                <div className="att-day-lieu-actions">
                                  <button
                                    type="button"
                                    className="att-day-btn att-day-btn-primary"
                                    disabled={acceptingKey === `${row.employeeId}-0.5`}
                                    onClick={() => handleAcceptLieu(row.employeeId, 0.5)}
                                  >
                                    0.5 day
                                  </button>
                                  <button
                                    type="button"
                                    className="att-day-btn att-day-btn-primary"
                                    disabled={acceptingKey === `${row.employeeId}-1`}
                                    onClick={() => handleAcceptLieu(row.employeeId, 1)}
                                  >
                                    1 day
                                  </button>
                                </div>
                              ) : null}
                            </>
                          ) : (
                            <span className="att-day-muted">Not assigned</span>
                          )}
                        </td>
                      ) : null}
                    </tr>
                  );
                })
              )}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}
