import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { hrSupportRequest } from '../api/hrSupportApi';
import { buildEmployeeLeaveBalanceCards, sumLeaveBalanceTotals } from '../utils/employeeLeaveBalances';
import { isAutoGeneratedLeave, leaveStatusLabel, overlookingStatusLabel } from '../utils/hrStatusLabels';
import { getEmployeeGreetingName } from '../utils/employeeDisplay';
import CalendarMonthGrid from '../components/CalendarMonthGrid';
import LeaveBalanceCards from '../components/LeaveBalanceCards';
import { formatApiDateDisplay } from '../utils/formatApiDate';

function DonutChart({ cards }) {
  const totals = sumLeaveBalanceTotals(cards);
  const available = totals.available;
  const used = totals.used;
  const total = Math.max(1, available + used);
  const radius = 44;
  const sw = 16;
  const circ = 2 * Math.PI * radius;
  const segments = [
    { key: 'available', value: available, color: '#0b6ea8', label: 'Available' },
    { key: 'used', value: used, color: '#f97316', label: 'Used' },
  ].filter((s) => s.value > 0);
  let progress = 0;
  const paths = segments.map((seg) => {
    const segLen = (seg.value / total) * circ;
    const offset = circ - progress;
    progress += segLen;
    return { ...seg, dasharray: `${segLen} ${circ - segLen}`, dashoffset: offset };
  });

  return (
    <div className="hrsup-donut-wrap">
      <div className="hrsup-donut-svg-wrap">
        <svg width={108} height={108} viewBox="0 0 120 120">
          <circle cx={60} cy={60} r={radius} stroke="#e2e8f0" strokeWidth={sw} fill="none" />
          {paths.map((p) => (
            <circle
              key={p.key}
              cx={60} cy={60} r={radius}
              stroke={p.color}
              strokeWidth={sw}
              fill="none"
              strokeDasharray={p.dasharray}
              strokeDashoffset={p.dashoffset}
              strokeLinecap="round"
              transform="rotate(-90 60 60)"
            />
          ))}
        </svg>
        <div className="hrsup-donut-center">
          <span className="hrsup-donut-center-value">{available + used}</span>
          <span className="hrsup-donut-center-label">Total</span>
        </div>
      </div>
      <div className="hrsup-donut-legend">
        {segments.map((seg) => (
          <div key={seg.key} className="hrsup-legend-row">
            <span className="hrsup-legend-dot" style={{ backgroundColor: seg.color }} />
            <span className="hrsup-legend-label">{seg.label}</span>
            <span className="hrsup-legend-value">{seg.value} ({Math.round((seg.value / total) * 100)}%)</span>
          </div>
        ))}
      </div>
    </div>
  );
}

function formatDate(value) {
  return formatApiDateDisplay(value, '—');
}

export default function HrSupportHomeTab({ token, homeData, profile, balances, policySummary, leaveTypes, overlookingInbox, loading, refreshing, refresh, actOverlookingDecision }) {
  const [showLeaveBalances, setShowLeaveBalances] = useState(false);
  const [calendarMonth, setCalendarMonth] = useState(() => {
    const now = new Date();
    return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`;
  });
  const [calendarData, setCalendarData] = useState(null);
  const [calDetailDate, setCalDetailDate] = useState(null);
  const [calDetailInfo, setCalDetailInfo] = useState(null);

  const leaveBalanceCards = useMemo(
    () => buildEmployeeLeaveBalanceCards(
      leaveTypes,
      policySummary,
      balances,
      profile?.allowedLeaveTypeCodes || profile?.allowed_leave_type_codes || null,
    ),
    [leaveTypes, policySummary, balances, profile?.allowedLeaveTypeCodes, profile?.allowed_leave_type_codes],
  );
  const leaveTypeNames = useMemo(
    () => leaveBalanceCards.map((c) => c.title).join(', '),
    [leaveBalanceCards],
  );

  const loadCalendar = useCallback(async (ym) => {
    if (!token) return;
    try {
      const data = await hrSupportRequest('/api/hr/calendar/month', token, { method: 'POST', body: JSON.stringify({ yearMonth: ym }) });
      setCalendarData(data || null);
    } catch { /* ignore */ }
  }, [token]);

  useEffect(() => { loadCalendar(calendarMonth); }, [calendarMonth, loadCalendar]);

  const shiftMonth = (dir) => {
    const [y, m] = calendarMonth.split('-').map(Number);
    const d = new Date(y, m - 1 + dir, 1);
    setCalendarMonth(`${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`);
  };

  const monthLabel = useMemo(() => {
    const [y, m] = calendarMonth.split('-').map(Number);
    return new Date(y, m - 1, 1).toLocaleString(undefined, { month: 'long', year: 'numeric' });
  }, [calendarMonth]);

  const handleDayClick = (dateKey) => {
    const details = calendarData?.leaveDetailsByDate?.[dateKey];
    const attendance = calendarData?.attendanceDetailsByDate?.[dateKey];
    setCalDetailDate(dateKey);
    setCalDetailInfo({ leaves: Array.isArray(details) ? details : [], attendance: attendance || null });
  };

  if (showLeaveBalances) {
    return (
      <div>
        <button type="button" className="hrsup-btn hrsup-btn--secondary hrsup-btn--sm" style={{ marginBottom: 12 }} onClick={() => setShowLeaveBalances(false)}>← Back</button>
        <div className="hrsup-card">
          <div className="hrsup-card-head">
            <h3 className="hrsup-card-title" style={{ margin: 0 }}>Your Leave Balances</h3>
            <button type="button" className="hrsup-refresh-btn" onClick={refresh} disabled={refreshing}>
              <span className={refreshing ? 'hrsup-spin' : ''}>↻</span>
            </button>
          </div>
          <LeaveBalanceCards cards={leaveBalanceCards} />
        </div>
      </div>
    );
  }

  return (
    <div>
      {/* Hero */}
      <div className="hrsup-hero">
        <p className="hrsup-hero-name">Hi, {getEmployeeGreetingName(profile)}</p>
        <p className="hrsup-hero-meta">
          {profile?.department || profile?.designation || 'Employee'}
          {profile?.joinedDate ? ` · Joined ${formatDate(profile.joinedDate)}` : ''}
        </p>
      </div>

      <div className="hrsup-chart-card" onClick={() => setShowLeaveBalances(true)} role="button" tabIndex={0} onKeyDown={(e) => e.key === 'Enter' && setShowLeaveBalances(true)}>
        <div className="hrsup-card-head" style={{ marginBottom: 0 }}>
          <span className="hrsup-section-label">Leave balance</span>
          <button
            type="button"
            className="hrsup-refresh-btn"
            onClick={(e) => { e.stopPropagation(); refresh(); }}
            disabled={refreshing}
          >
            <span className={refreshing ? 'hrsup-spin' : ''}>↻</span>
          </button>
        </div>
        {leaveTypeNames && (
          <p className="hrsup-section-hint">{leaveTypeNames} · tap for details</p>
        )}
        {leaveBalanceCards.length > 0 ? (
          <DonutChart cards={leaveBalanceCards} />
        ) : (
          <p className="hrsup-empty">
            {loading
              ? 'Loading…'
              : (profile?.leaveAvailabilityNotice
                || 'Leave availability is not set for your profile. Please contact HR to assign your leave types.')}
          </p>
        )}
      </div>

      {/* Overlooking inbox */}
      {overlookingInbox && overlookingInbox.length > 0 && (
        <div className="hrsup-card">
          <h3 className="hrsup-card-title">Overlooking Requests</h3>
          {overlookingInbox.map((item) => (
            <div key={`overlook-${item.id}`} className="hrsup-overlook-card">
              <div className="hrsup-overlook-top">
                <div>
                  <div className="hrsup-list-title">{item.employeeName} — {item.leaveTypeName}</div>
                  <div className="hrsup-list-meta">{formatDate(item.start_date)} – {formatDate(item.end_date)}</div>
                  <div className="hrsup-list-meta">Status: {overlookingStatusLabel(item.overlooking_status || 'pending')}</div>
                </div>
              </div>
              {String(item.overlooking_status || '') === 'pending' && (
                <div className="hrsup-list-row-actions">
                  <button type="button" className="hrsup-btn hrsup-btn--primary hrsup-btn--sm" onClick={() => actOverlookingDecision(item.id, 'accept')}>Accept</button>
                  <button type="button" className="hrsup-btn hrsup-btn--danger hrsup-btn--sm" onClick={() => actOverlookingDecision(item.id, 'decline')}>Decline</button>
                </div>
              )}
              {String(item.overlooking_status || '') === 'declined' && item.reject_reason_overlooking && (
                <p style={{ margin: '6px 0 0', fontSize: 12, color: '#dc2626', fontStyle: 'italic' }}>Declined: {item.reject_reason_overlooking}</p>
              )}
            </div>
          ))}
        </div>
      )}

      {/* Monthly Calendar */}
      <div className="hrsup-card">
        <div className="hrsup-card-head">
          <button type="button" className="hrsup-btn hrsup-btn--secondary hrsup-btn--sm" onClick={() => shiftMonth(-1)}>← Prev</button>
          <h3 className="hrsup-card-title" style={{ margin: 0 }}>{monthLabel}</h3>
          <button type="button" className="hrsup-btn hrsup-btn--secondary hrsup-btn--sm" onClick={() => shiftMonth(1)}>Next →</button>
        </div>
        <CalendarMonthGrid
          yearMonth={calendarMonth}
          calendarData={calendarData}
          onDayClick={handleDayClick}
        />
      </div>

      {/* Day detail popup */}
      {calDetailDate && calDetailInfo && (
        <div className="hrsup-modal-overlay" onClick={() => { setCalDetailDate(null); setCalDetailInfo(null); }}>
          <div className="hrsup-modal" onClick={(e) => e.stopPropagation()}>
            <div className="hrsup-modal-head">
              <h3 className="hrsup-modal-title">{new Date(`${calDetailDate}T12:00:00`).toLocaleDateString(undefined, { weekday: 'long', day: 'numeric', month: 'long' })}</h3>
              <button type="button" className="hrsup-modal-close" onClick={() => { setCalDetailDate(null); setCalDetailInfo(null); }}>✕</button>
            </div>
            <div className="hrsup-modal-body">
              {calDetailInfo.attendance && (
                <div style={{ marginBottom: 12 }}>
                  <p style={{ fontWeight: 700, fontSize: 13, marginBottom: 6 }}>Attendance</p>
                  <p style={{ fontSize: 13, color: '#64748b', margin: 0 }}>
                    In: {calDetailInfo.attendance.mark_in ? new Date(String(calDetailInfo.attendance.mark_in).replace(' ', 'T')).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : '—'}
                    {' · '}
                    Out: {calDetailInfo.attendance.mark_out ? new Date(String(calDetailInfo.attendance.mark_out).replace(' ', 'T')).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : '—'}
                  </p>
                </div>
              )}
              {calDetailInfo.leaves.length > 0 && (
                <div>
                  <p style={{ fontWeight: 700, fontSize: 13, marginBottom: 6 }}>Leaves</p>
                  {calDetailInfo.leaves.map((lv, idx) => (
                    <div key={idx} style={{ fontSize: 13, color: '#64748b', marginBottom: 6, padding: '6px 10px', background: '#f8fafc', borderRadius: 8, border: '1px solid #e2e8f0' }}>
                      <span style={{ fontWeight: 700, color: '#0f172a' }}>{lv.leaveTypeName || lv.leave_type_code}</span>
                      {' · '}
                      {lv.requestMode?.replace('_', ' ')}
                      {' · '}
                      <span style={{ color: lv.status === 'approved' ? '#16a34a' : lv.status?.startsWith('pending') ? '#d97706' : '#64748b' }}>{leaveStatusLabel(lv.status)}</span>
                      {isAutoGeneratedLeave(lv) && <span style={{ marginLeft: 6, color: '#ea580c', fontWeight: 700 }}>Auto</span>}
                    </div>
                  ))}
                </div>
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
